import type { ChocolateFlavor, Product } from "@/types/listing";

export const PRODUCTS: Product[] = [
  {
    id: "1",
    name: "SNICKERS",
    price: 28.84,
    desc: "SNICKERS, TWIX, & MILKY WAY Minis Chocolate Candy Bars Variety Pack, 150 Ct Bulk Bag",
    images: ["snickers_1.png", "snickers_2.png"],
    flavor: "milk",
  },
  {
    id: "2",
    name: "Pepperidge Farm",
    price: 6.3,
    desc: "Pepperidge Farm Chocolate Collection, 7 Cookie Varieties, 13-oz Box",
    images: ["pepperidge_1.png", "pepperidge_2.png", "pepperidge_3.png"],
    flavor: "dark",
  },
  {
    id: "3",
    name: "HERSHEY'S",
    price: 13.21,
    desc: "HERSHEY'S Miniatures Assorted Chocolate Candy Party Pack, Halloween Candy, 35.9 oz",
    images: ["hersheys_1.png", "hersheys_2.png"],
    flavor: "milk",
  },
  {
    id: "4",
    name: "M&M'S",
    price: 28.84,
    desc: "M&M'S Peanut Candy Jars, Assorted Chocolate Candies, Party Size Bulk, Movie Night Treats, Bulk Chocolate Candy, Buffet Chocolates, Resealable and Recyclable, 23 Oz Each, Pack of 2",
    images: ["mm_1.png", "mm_2.png", "mm_3.png", "mm_4.png"],
    flavor: "milk",
  },
  {
    id: "5",
    name: "DOVE PROMISES",
    price: 47.74,
    desc: "DOVE PROMISES Milk Chocolate, Dark Chocolate & Caramel Chocolate Mothers Day Candy Variety Bag, 38.9oz",
    images: ["dove_1.png", "dove_2.png"],
    flavor: "dark",
  },
  {
    id: "6",
    name: "Kinder BUeno",
    price: 23.24,
    desc: "Kinder Bueno Milk Chocolate and Hazelnut Cream, Bulk 20 Pack, 2 Individually Wrapped Chocolate Bars Per Pack, 30 oz",
    images: ["kinder_1.png", "kinder_2.png"],
    flavor: "milk",
  },
  {
    id: "7",
    name: "REESE'S",
    price: 14.84,
    desc: "REESE'S Milk Chocolate Snack Size Peanut Butter Cups, Candy Bag, Halloween Candy, 33 oz (60 Pieces)",
    images: ["reese_1.png", "reese_2.png"],
    flavor: "mixed",
  },
  {
    id: "8",
    name: "SANDERS",
    price: 17.58,
    desc: "Sanders Milk Chocolate Sea Salt Caramels (32 oz Tub) – Handcrafted Small Batch Slow Cooked Caramel, Sea Salt Chocolate with Rich Indulgent Flavor, Sweet & Salty",
    images: ["sanders_1.png", "sanders_2.png", "sanders_3.png"],
    flavor: "milk",
  },
  {
    id: "9",
    name: "Tabs",
    price: 29.99,
    desc: "Tabs Chocolate Squares for Couples (1 Box) - Dark Chocolate Bar to Improve Mood - Vegetarian, Gluten-Free for Men & Women",
    images: ["tabs_1.png", "tabs_2.png"],
    flavor: "dark",
  },
  {
    id: "10",
    name: "Meiji Hello Panda",
    price: 29.99,
    desc: "Meiji Hello Panda Cookies, Chocolate Crème Filled - 32 Count, 0.75oz Packages - Bite Sized Cookies with Fun Panda Sports",
    images: ["meiji_1.png"],
    flavor: "milk",
  },
  {
    id: "11",
    name: "Milka",
    price: 20,
    desc: "Milka Assorted Chocolates Variety Pack of 8 Bars (Bundle #2)",
    images: ["milka_1.png"],
    flavor: "milk",
  },
  {
    id: "12",
    name: "Sanders Dark",
    price: 9.99,
    desc: "Sanders Dark Chocolate Sea Salt Caramel Thins - 18 oz. Tub",
    images: ["sanders_thin_1.png"],
    flavor: "milk",
  },
  {
    id: "13",
    name: "AWAKE",
    price: 9.99,
    desc: "AWAKE - Caffeinated Chocolate Bars - Dark Chocolate, 12 Bars - 100mg Caffeine - 1 Bar Equals 1 Cup of Coffee - Individually Wrapped Energy - Fairtrade, Gluten Free, Non GMO, Kosher - 1.34oz",
    images: ["awake_1.png", "awake_2.png", "awake_.png"],
    flavor: "milk",
  },
  {
    id: "14",
    name: "Swiss Miss Milk",
    price: 29.34,
    desc: "Swiss Miss Milk Chocolate Hot Cocoa, Single-Serve Keurig K-Cup Pods, Hot Chocolate, 44 Count",
    images: ["swiss_miss_1.png"],
    flavor: "milk",
  },
  {
    id: "15",
    name: "Trader Joe's",
    price: 29.34,
    desc: "Trader Joe's 72% Cacao Belgian Dark Chocolate Bars (1 Pack of 3)",
    images: [""],
    flavor: "dark",
  },
  {
    id: "16",
    name: "SKITTLES",
    price: 29.5,
    desc: "SKITTLES & STARBURST Assorted Candy Variety Pack for Holidays, Candy Assortment, Party Favors, 62.79 oz (30 Count) Bulk Box",
    images: ["skittles_1.png", "skittles_1.png"],
    flavor: "mixed",
  },
].map((item) => ({
  ...item,
  rating: Math.floor(Math.random() * 6),
  flavor: item.flavor as ChocolateFlavor,
  images: item.images.map((img) =>
    img ? `/images/products/${img}` : "/images/no_image.png"
  ),
}));
